#version: "3.9"
#services:
#  mongodbservice:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
#    container_name: mongo-track-container
#    networks:
#      - product-net
#  user-auth-service:
#    container_name: product-service
#    build: ./
#    networks:
#      - product-net
#    ports:
#      - "65108:65108"
#    depends_on:
#      - mongodbservice
#    restart: always
#networks:
#  track-net:
#    driver: bridge